### ISSUE TITLE
persist.js security issue in FF6

### ISSUE THREAD

**Issue by jexp** [jexp/mg_client#13]
Ah, folgende Fehler hab ich da, leider wohl immer noch die mit dem persist.
Error: uncaught exception: [Exception... "Security error"  code: "1000" nsresult: "0x805303e8 (NS_ERROR_DOM_SECURITY_ERR)"  location: "http://server.mesirii.de/~mg/js/persist/persist-min.js Line: 30"]

Error: Persist is not defined
Source File: http://server.mesirii.de/~mg/js/mg_client/mg_client_persist.js
Line: 1

Error: store is undefined
Source File: http://server.mesirii.de/~mg/js/mg_client/mg_client_persist.js
Line: 42

**Comment by zesstra** [comment]
Das mit dem persist-Fehler scheint was lokales in meinem profil zu sein. :-(
Bei einem anderen User tritt das so nicht auf und die Seite wird scheinbar vollstaendig geladen.
Jetzt muss ich nur rausfinden, wie ich mein Profil repariere. :-(

**Comment by zesstra** [comment]
Argl. Gnaaaaa. Weisst Du, woran es lag? An Cookies, die ich standardmaessig nicht akzeptiere.

**Comment by jexp** [comment]
Hmm dann entferne ich mal cookies als storage. Da passt eh nix rein.

**Comment by zesstra** [comment]
Cool, danke. :-)

**Comment by zesstra** [comment]
Hmpf. Schlechte Nachricht: es passiert immer noch, wenn man keine Cookies erlaubt. (gerade wieder fuer mg.mud.de passiert. _g_)

**Comment by jexp** [comment]
Ich stell nochmal was um, ggf. hilft es nochmal. Ich hab gelesen dass da "globalstorage" auch disabled ist, wenn cookies disabled sind. Irgendwie doof.

Ich hab das mal aktualisiert, das vorher war von 2007.

https://github.com/jeremydurham/persist-js

**Comment by zesstra** [comment]
Das sortierte ich auch in die wichtigeren UI-Bugs ein, weil das fuer Nutzer so aussieht, als sei die UI bzw. der Client kaputt und man keinen Hinweis hat, woran es liegt. Wenn man persist.js die Cookies nicht abgewoehnen kann, muesste man evtl. gucken, ob man Cookies speichern kann und ne Warnung ausgeben, wenn nicht...

**Comment by jexp** [comment]
Hmm hab mal noch ein bisschen Fehlerbehandlung zu persist.js hinzugefügt und einen "NOOP" store, der das ganze nur in einem objekt speichert. Damit sollte es jetzt eigentlich gehen, auch wenn sonst nix geht.
