### ISSUE TITLE
Konversion nach ASCII 

### ISSUE THREAD

**Issue by zesstra** [jexp/mg_client#21]
Wenn das Encoding/Charset des Browsers dem Proxy bekannt ist, koennte der Proxy vermutlich ohne grossen Aufstand nach ASCII/TRANSLIT konvertieren.
Andere Moeglichkeit: der client macht es direkt.

**Comment by zesstra** [comment]
Das ganze sollte sich bei Nutzung von https://github.com/bnoordhuis/node-iconv mit wenigen Zeilen erledigen lassen.
Nachteil ist aber, dass man dann nodejs und das node-iconv Modul braucht... Aber das waere relativ vernuenftig ohne selber mit regexp & Co rumbasteln zu muessen...
Was meinst Du dazu?

**Comment by zesstra** [comment]
Ah, Dein Proxy verwendete ja ohnehin nodejs, d.h. da koennte man das unterbringen. Könnte denn der Client unabhaengig von Browsereinstellungen immer das gleiche Encoding verwenden/liefern, sagen UTF8 oder UTF16?

**Comment by jexp** [comment]
Danke fürs Einbauen
