### ISSUE TITLE
Charakter-Anlage mittels Menü

### ISSUE THREAD

**Issue by jexp** [jexp/mg_client#26]
wie waere es denn, wenn man das Anlegen von Neuspielern etwas mehr Richtung
anklicken aus Auswaehlen in Menues gestaltet. Also sprich, ich klick ein 
Bildchen fuer die Rasse und maennlich/weiblich an und bekomme ein
Popup fuer Name und Passwort? Und erst danach lande ich im MudScroll. 
Wuerde meiner Meinung nach die Hemmschwelle erstmal senken, weil es eine
bekanntere Mechanik ist.

Guck Dir mal an, wie die das im BatMud machen mit der Charaktererschaffung.

**Comment by zesstra** [comment]
Einerseits ja. Anderseits erzeugt es aber IMHO auch ein falsches Bild, denn der Text kommt dann halt 30s spaeter.
(Und blindengerecht ist das eher nicht, d.h. das muesste man als Option anbieten.)

**Comment by kaeptnahab** [comment]
Kann man nicht auf die Namensabfrage beim Login triggern und dann einen Button "Neuen Spieler anlegen" als Overlay im Hauptfenster anzeigen? Wenn man das möchte, klickt man dann da drauf und kann seinen Char zusammenstellen. Wenn manuell "neu" oder ein Name eingegeben wird, verschwindet der wieder und der Login bzw. die Charaktererstellung startet wie gewohnt.

**Comment by jexp** [comment]
login fenster + neuspieleranlage via dialog
