### ISSUE TITLE
Timeout-Meldung bei Login wird nicht direkt angezeigt.

### ISSUE THREAD

**Issue by zesstra** [jexp/mg_client#33]
Sollte doch der Timeout zuschlagen und die Verbindung getrennt werden, wird diese nicht direkt dem Spieler angezeigt, sondern erst wenn der was sendet. Ich nehme an, dass haengt mit der Prompterkennung zusammen? Ggf. laesst sich da auch ein Prompt faken, wenn es daran liegen sollte.

**Comment by jexp** [comment]
timeout wird jetzt angezeigt, und da verzögert verbunden wird, ist es auch nicht mehr das problem
