### ISSUE TITLE
Popup-Menü

### ISSUE THREAD

**Issue by kaeptnahab** [jexp/mg_client#38]
Das Popup-Menü in der kwer-Liste verhält sich seltsam. Bei Magiern wird nur "unt/nimm/trage/toete" angezeigt, bei Spielern und Sehern hingegen "reden/finger/rknuddel".

**Comment by kaeptnahab** [comment]
Ich denke, wir haben gerade den Grund fuer das Verhalten gefunden: Alle Namen, die eine ANSI-Auszeichnung tragen (rot für Erwartete, unterstrichen für Magier) werden nicht als Spieler erkannt und es wird demzufolge das falsche Menü angezeigt.

**Comment by jexp** [comment]
sollte behoben sein, da die ansi-markups jetzt korrekt entfernt werden
