### ISSUE TITLE
UI: [Optional] Text im Hauptfenster weglassen?

### ISSUE THREAD

**Issue by Gloinson** [jexp/mg_client#39]
Der Teddy zB könnte nur noch optional im Hauptfenster seine Textmeldungen scrollen, wenn man "Status" an hat.

Ähnlich gestaltet sich das mit kwer oder der Langbeschreibung eines Raumes: es könnte im Hauptfenster nichts bzw. nur der Kurztext des Raumes erscheinen, wenn "MUD"->"Anwesende" oder "MUD"->"Ort" an ist.

**Comment by jexp** [comment]
Mal für diverse Sachen eingebaut, für anderes kann das simpel nachgerüstet werden.
