### ISSUE TITLE
Umbruch im Hauptfenster

### ISSUE THREAD

**Issue by kaeptnahab** [jexp/mg_client#43]
... funktioniert nicht (Beta-Umgebung). Sagte Miril grad. Fiel bei der Ausgabe von "denke <langertext>" auf.

**Comment by jexp** [comment]
Hmm hab mal bei Maha\* geschaut, es scheinen die Zeilen zu sein, die vom Mud nicht vor-umgebrochen werden.

Gute Frage was man damit im Client macht - entweder hart auf 78 Zeichen umbrechen oder mit Word-Wrap. Zur Zeit ist das ja nur ein &lt;pre&gt; für die Anzeige, weiss nicht, ob man das in ein textarea umwandeln sollte, weil das ja den Umbruch von selbst macht.

**Comment by zesstra** [comment]
Also, an sich sind ueberlange zeilen (>80 oder telnet-ausgehandelte Zeilenbreite, wenn mehr als 80) ein Fehler des Muds... Und nen Fehler absetzen, damit es im Mud gefixt wird, waer gut. In TF & Co faellt der Fehler halt meist gar nicht auf, insofern ist das auch von Vorteil, wenn er im Webclient auffaellt. Anderseits ist das fuer Neuspieler nicht so toll...

**Comment by jexp** [comment]
Ok, dann lass ich das mal so stehen und mach nix im Client. Ich könnte maximal nen Trigger einbauen, der überlange Zeilen hervorhebt?

**Comment by zesstra** [comment]
Mhmm, ja, das waere ne Idee. Ich weiss nur nicht, ob man als Neuling damit was anfangen kann. Vielleicht mal abwarten, wie haeufig das vorkommt?
