### ISSUE TITLE
Trigger-Update Spielerstatusreports

### ISSUE THREAD

**Issue by zesstra** [jexp/mg_client#45]
In Kürze werden die neuen Spielerstatusreports fertig. Da kommen die Reports direkt aus den Spielerobjekte und der Teddy aus der Nibelungenquest ist nicht mehr noetig. Es wird konfigurierbar sein, ueber was man benachrichtigt werden moechte:
report alle | ein | aus | kp | lp | gift | vorsicht

Die Meldungen sind dann wie folgt:
Du hast jetzt 200 Lebenspunkte.
Du hast jetzt 206 Konzentrationspunkte.
Du hast eine sehr ernste Vergiftung.
Du hast eine gefaehrliche Vergiftung.
Du hast eine leichte Vergiftung.
Du hast keine Vergiftung.
Vorsicht: 1
Vorsicht: 1, Fluchtrichtung: osten

Report fuer LP geht von Anfang an, der Rest wird mit einfachen Anfaengerquests freigeschaltet, Fluchtrichtung ab Seher.

**Comment by zesstra** [comment]
Achja, die Meldungen kommen bei jeder Veraenderung der zugrunde liegenden Properties im Spielerobjekt.

**Comment by jexp** [comment]
Ah, das wollte ich noch wissen.

Im Team-Objekt gibt es ein team autoinform, wär toll, wenn das für alle Team-Mitglieder zur Verfügung stände.

**Comment by zesstra** [comment]
Ja, das haben wir auch diskutiert und ist IMHO mittelfristig geplant, sobald sich irgendjemand mit dem Teamobjekt auseinandergesetzt hat. Evtl. kann da auch Gloinson was machen, der kennt das Ding vermutlich besser als alle anderen anwesenden magier...

**Comment by jexp** [comment]
Ok, eingebaut.

**Comment by zesstra** [comment]
Hihi. Ich hab vorhin auch dran gebastelt und war beim dritten als Deine Mail reinkam. Hatte sogar selber gefunden, wo die eingetragen werden. ;-)
