### ISSUE TITLE
Auswahl in Anwesenheitsliste wirkt immer auf Zook

### ISSUE THREAD

**Issue by zesstra** [jexp/mg_client#48]
Wenn ich einen Char in der Anwesenheitsliste auswähle und "Reden" anklicke, geht bei mir immer ein mit Zook beschriftetes Chat-Tab auf. Ich vermute, es wird immer der letzte Char in der Liste ausgewählt.
Gleiches gilt fuer die anderen Aktionen (z.B. finger).

**Comment by zesstra** [comment]
Ah, Klarstellung: gemeint ist das Anwesenheitsfenster links ueber den Kompass-Buttons.

**Comment by jexp** [comment]
ist wahrscheinlich nur goettliches vordraengeln 
ich untersag ihm das mal

mobile mail please excuse brevity and typos

Am 26.09.2011 um 16:23 schrieb Dominik Schäfer reply@reply.github.com:

**Comment by kaeptnahab** [comment]
Nein, nicht auf Zook. Das geht immer auf den letzten Spieler in der Liste, bei mir wars grad Xutelius.

**Comment by zesstra** [comment]
Das schrieb ich ja. Zweiter Satz. ;-)

**Comment by kaeptnahab** [comment]
Eh. Ja. Sollte auch mehr ne Bestätigung Deiner Vermutung werden. Ging daneben. ;-)

**Comment by jexp** [comment]
fixed, war ein late-binding einer variable innerhalb einer closure

habs jetzt durch nen zugriff auf den $(this).text() des html elements ersetzt, irgendwie hässlich aber ich hab grad keine andere idee, wie ich die variable fixieren kann.
