### ISSUE TITLE
Rubrikauswahl bei Antwort in MPA

### ISSUE THREAD

**Issue by zesstra** [jexp/mg_client#50]
Wenn ich auf einen Artikel antworte, habe ich zwar so eine Dropdownliste fuer die Rubrikauswahl, hab aber nur die Rubrik zur Auswahl, in der der beantwortete Artikel steht.

**Comment by jexp** [comment]
hatte ich ganz vergessen dass man ja auch in ner anderen rubrik antworten kann

mobile mail please excuse brevity and typos

Am 26.09.2011 um 16:34 schrieb Dominik Schäfer reply@reply.github.com:

**Comment by jexp** [comment]
fixed, aktuelle rubrik ist jetzt voreingestellt
