### ISSUE TITLE
Gaggen von umgeleiteten Meldungen

### ISSUE THREAD

**Issue by zesstra** [jexp/mg_client#51]
Die Ebenenmeldungen werden ja jetzt im Hauptfenster nicht mehr angezeigt. Ich hab das Kommunikationsfenster mit den Ebenen normalerweise nicht offen, weil mein Bildschirm zu klein ist und ich das eh lieber im hauptfenster lese.
Die Folge ist, dass ich die Ebenen nicht mehr lese. Wenn das Fenster nicht offen ist, wird der Text da aber auch nicht reingeschrieben, d.h. ich kann auch im Nachhinein nicht einfach das Fenster aufklappen.

Kurz: das Gaggen von standardmässig umgeleitetem Text muss konfigurierbar sein.

Und eigentlich: zur Zeit sehe ich eine ziemlich grosse Wahrscheinlichkeit, dass ein Anfaenger das Kommunikationsfenster einfach zumacht, weil er Platz auf dem Screen haben will. Ab dann gehen ihm alle Ebenen verloren, was ziemlich katastrophal fuer Anfaenger ist, weil er keine Hilfe mehr kriegt, sich ignoriert fuehlt etc.

Ich bin tatsaechlich dafuer, das Gaggen zu unterlassen, wenn das Fenster, in das umgeleitet wird, gar nicht eingeblendet ist.

Das ganze ist uebertragbar auf andere Dinge, die umgeleitet und dann im Hauptfenster gegaggt werden.

**Comment by zesstra** [comment]
Oeh. Ich glaube, Du kannst den ganzen sermon da direkt nach /dev/null befoerdern, weil das gar nicht stimmt. Mein Testie schien alle Ebenen ausgeschaltet zu haben. _fluch_
Vergiss es einfach. _argl_

**Comment by jexp** [comment]
das war ein versehen, sollte nicht so sein

mobile mail please excuse brevity and typos

Am 26.09.2011 um 16:41 schrieb Dominik Schäfer reply@reply.github.com:
