### ISSUE TITLE
Zeilenzahl vordefinieren

### ISSUE THREAD

**Issue by kaeptnahab** [jexp/mg_client#73]
Gerade hatte ein Spieler das Problem, dass das more-Prompt nicht sauber angezeigt wurde, und er daher nicht weiterkam. Als Workaround hat er dann "zeilen 0" eingestellt, und ich denke, dass das vielleicht grundsätzlich nicht verkehrt waere. Man kann ja immer noch mit dem Scrollbalken nachlesen. 

Auf irgendeine Weise hat er dann aber an der Stelle auch einen "Error: EPIPE, Broken pipe" bekommen, keine Ahnung, ob das kausal damit zusammenhing, aber das sollte man auf jeden Fall auch nochmal nachverfolgen.

**Comment by Kebap** [comment]
Kann geschlossen werden, "zeilen 0" ist default bei Neuspielern, seit 2012.

**Comment by zesstra** [comment]
Bin mir nicht sicher, ob das mit dem "zeilen 0" immer so bleibt - eigentlich waere es besser, wenn die Clients das mit Telnet Negotiations aushandeln.
Insofern können wir das jetzt zumachen, aber evtl. muss man sich da nochmal mit befassen.
